<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2005-2006 The Apache Software Foundation or its licensors, as applicable

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!DOCTYPE Test SYSTEM "test.dtd">
<!--
Author: Ilia A. Leviev
Version: $Revision: 1.3 $
-->
<Test
  ID="athrow0201"
  date-of-creation="2004-11-18"
  timeout="1"
  >	
  <Author value="Ilia A. Leviev"/>
  <Description>    
    Instruction athrow throw exception of TestException type which is java.lang.Throwable subclass, then:
    If VM caught exception which is instance of TestException- test pass;
    If VM not throw any exception or throw other exception - test fail;
 
    Covered assertions assert_instr2a118 assert_instr2a119 assert_instr2a120 assert_class458 assert_class460 
  </Description>

  <Source name="athrow0201p.j"/>

  <Runner ID="Runtime">
    <Param name="toRun" value="org.apache.harmony.vts.test.vm.jvms.instructions.exceptions.athrow.athrow02.athrow0201.athrow0201p"/>                          
</Runner>
</Test>
